# Generated by Django 4.1.7 on 2023-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('Postal_code', models.CharField(max_length=50)),
                ('Select_Medicine', models.CharField(max_length=50)),
                ('Payment', models.CharField(max_length=50)),
            ],
        ),
    ]
