# Generated by Django 4.1.7 on 2023-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease1_title', models.CharField(max_length=50)),
                ('disease1_desc', models.TextField()),
            ],
        ),
    ]
