# Generated by Django 4.1.7 on 2023-04-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service',
        ),
    ]
