# Generated by Django 4.1.7 on 2023-04-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_research_img_reserach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='img_Reserach',
            new_name='img_Research',
        ),
    ]
