# Generated by Django 4.1.7 on 2023-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_desc', models.TextField()),
                ('Medicine_title', models.CharField(max_length=50)),
                ('Pack_size', models.CharField(max_length=50)),
                ('Composition', models.CharField(max_length=50)),
                ('Mode_of_action', models.CharField(max_length=50)),
                ('Formulation', models.CharField(max_length=50)),
                ('Crops', models.CharField(max_length=50)),
                ('Pests', models.CharField(max_length=50)),
                ('Dose', models.CharField(max_length=50)),
                ('Medicine_img', models.FileField(default=None, max_length=250, null=True, upload_to='medicine2/')),
            ],
        ),
    ]
