# Generated by Django 4.1.7 on 2023-04-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_title', models.CharField(max_length=50)),
                ('disease_desc', models.TextField()),
                ('disease_Img', models.ImageField(upload_to='Balck Scruf.png/')),
            ],
        ),
    ]
