# Generated by Django 4.1.7 on 2023-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_remove_disease_disease_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='disease_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='medicine2/'),
        ),
    ]
